name: gully_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+10

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  get: ^5.0.0-release-candidate-4
  pin_code_fields: ^8.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  device_preview: ^1.1.0
  logger: ^2.0.1
  shared_preferences: ^2.2.0
  firebase_auth: ^4.8.0
  google_sign_in: ^6.1.4
  firebase_core: ^2.15.1
  json_annotation: ^4.8.1
  intl: ^0.18.1
  image_picker: ^1.0.5
  google_maps_flutter: ^2.5.0
  google_places_flutter: ^2.0.6
  faker: ^2.1.0
  mime: ^1.0.4
  permission_handler: ^11.0.1
  geolocator: ^10.1.0
  cached_network_image: ^3.3.1
  geocoding: ^2.1.1
  socket_io_client: ^2.0.3+1
  flutter_widget_from_html: ^0.14.11
  firebase_messaging: ^14.7.10

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/.
  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham-Black.otf
          weight: 700
        - asset: assets/fonts/Gotham-Bold.otf
          weight: 600
        - asset: assets/fonts/GothamMedium.ttf
          weight: 500
        - asset: assets/fonts/Gotham-Light.otf
          weight: 300
        - asset: assets/fonts/Gotham-Thin.otf
          weight: 100
